// <auto-generated />
namespace WebBanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateDeleteUserWallet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDeleteUserWallet));
        
        string IMigrationMetadata.Id
        {
            get { return "202307260727376_updateDeleteUserWallet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
